### ISSUE TITLE
Version 1.0.5 doesn't exist?

### ISSUE THREAD

**Issue by d-scott** [calvinmetcalf/rollup-plugin-node-builtins#11]
Hi,

When I do an install:
`npm install --save-dev rollup-plugin-node-builtins`
 it shows up in my package.json's devDependencies as:
`"rollup-plugin-node-builtins": "^1.0.5"`

But there is no version 1.0.5. Consequently my build fails with the following error:
`Error: Cannot find module 'rollup-plugin-node-builtins'`

**Comment by d-scott** [comment]
Explicitly setting it to 1.0.4 works fine.

**Comment by calvinmetcalf** [comment]
should be fixed in 1.0.6

**Comment by kylegmaxwell** [comment]
yup, 1.0.6 is working for me, thanks!

**Comment by d-scott** [comment]
Works, cheers
