### ISSUE TITLE
error: Cannot find module 'rollup-plugin-node-globals/dist/buffer'

### ISSUE THREAD

**Issue by kylegmaxwell** [calvinmetcalf/rollup-plugin-node-builtins#13]
Hi, thank you for these plugins. I am using this one as well as rollup-plugin-node-globals and just started having an issue. It seems that you just released https://github.com/calvinmetcalf/rollup-plugin-node-globals/commit/6c47f086a25d9bf8fafaaaac75c8796bc71a7b7a, which does not work with https://npmcdn.com/rollup-plugin-node-builtins@1.0.7/src/index.js. I assume you are going to update that as well to use the new plugin, but currently I get an error: Cannot find module 'rollup-plugin-node-globals/dist/buffer'.

**Comment by calvinmetcalf** [comment]
oh right forgot about that one, yes will update tommorow

**Comment by calvinmetcalf** [comment]
fixed in 1.0.8

**Comment by kylegmaxwell** [comment]
Thanks!
