### ISSUE TITLE
TypeError: global$1.XMLHttpRequest is not a function

### ISSUE THREAD

**Issue by denneulin** [calvinmetcalf/rollup-plugin-node-builtins#25]
Hi,

I am using you plugin to bundle my project.
I am trying to include node_modules into bundle in order to deploy on AWS Lambda.

When I use rollup-plugin-node-builtins with rollup-plugin-node-globals, my bundle.js can not be used because of the line 20 of es6/http-lib/capability.js :
`xhr = new global.XMLHttpRequest()`

XMLHttpRequest does not exist on Node.js API.

What have I missed ?

**Comment by calvinmetcalf** [comment]
this is intended to provide the node libraries in the browser where they are not available.  just do a regular require for the node builtins you need, rollup should ignore it and lambda has the built in modules

**Comment by denneulin** [comment]
thanks for your help ;)

**Comment by vasiliulaura15** [comment]
Hi! I am hitting the same issue. In the code I don't have any imports for node builtins and I am still seeing this. How can I by pass this error?

**Comment by zingi** [comment]
I was able to fix the problem by swapping this:
```javascript
import got from 'got'
```
with that:
``` javascript
const got = require('got')
```
