### ISSUE TITLE
Error: Couldn't find preset "es2015-rollup" relative to directory

### ISSUE THREAD

**Issue by destroyerofbuilds** [calvinmetcalf/rollup-plugin-node-builtins#29]
After installing `rollup-plugin-node-builtins` within a RollupJS project of mine, I encountered the following error:

```
Error: Couldn't find preset "es2015-rollup" relative to directory "node_modules\\rollup-plugin-node-builtins" at error (node_modules\rollup\dist\rollup.js:170:12)
```

The error is identical to the same issue that effected `rollup-plugin-node-resolve` in rollup/rollup-plugin-node-resolve#27

This package is publishing its `.babelrc` file, so that when RollupJS attempts to interact with this package, while using the Babel Rollup plugin, it throws an error. That is because the `.babelrc` file references a preset that is not installed.

**Comment by calvinmetcalf** [comment]
checkout v2.1.2 should fix it

**Comment by ghost** [comment]
I just upgraded my project using `yarn`, and the error message no longer appears when I run Rollup.

Checking my `yarn.lock` file, I see version `2.1.2` in there.

So, yeah, works great! Thank you!
