### ISSUE TITLE
Clarification: order of builtins + globals plugins?

### ISSUE THREAD

**Issue by binarykitchen** [calvinmetcalf/rollup-plugin-node-builtins#32]
What's the rule when to put the builtins plugin before the globals plugin? Or the other way around? I see many examples which have a different order of these plugins which is kinda confusing.

Would be good to have a clarification on that here, or even better in the readme. Thanks!

**Comment by calvinmetcalf** [comment]
Take a look at the [config I published](https://github.com/calvinmetcalf/rollup-config-cjs/blob/15808cebf0a4571ce28c90daf331206a55498a40/index.js#L7-L18)

**Comment by binarykitchen** [comment]
thanks - can you explain why this order? why globals before the built-ins?

and the 2nd question:
what if more plugins are in play? for example those I have:

```
  plugins: [
    replace({'process.env.NODE_ENV': JSON.stringify('development')}),
    progress(),
    stylusCssModules({output: false}),
    alias({
      'readable-stream': 'stream'
    }),
    regenerator(),
    buble(),
    globals(),
    builtins(),
    nodeResolve({jsnext: true, browser: true}),
    commonjs(),
    json({preferConst: true}),
    filesize({showGzippedSize: false})
  ],
```

which produces this error:

```
bundling...
(602): package.json🚨   (buble plugin) Unexpected token (2:8)
undefined (2:8)
```

how would you investigate and proceed here? what's the recommendation how to fine-tune the order of rollup plugins?

**Comment by calvinmetcalf** [comment]
- autotransform is first because it's really a browserify thing so we don't want to do any rollup specific stuff until after
- globals is next
- builtins is after globals because it relies on some of the things globals does

I have not used these things on anything as extensive and complex as you are trying to do, you are in uncharted territory so I'm sorry if I can't give you much more information

**Comment by binarykitchen** [comment]
thanks - i just hope there will be more examples in the uncharted territory soon ...
