### ISSUE TITLE
Stream destroy

### ISSUE THREAD

**Issue by scola84** [calvinmetcalf/rollup-plugin-node-builtins#34]
From v8.0.0 a stream has a `destroy` method:

https://nodejs.org/en/blog/release/v8.0.0/#stream-api-improvements
https://nodejs.org/dist/latest-v8.x/docs/api/stream.html#stream_writable_destroy_error

Any plans to implement this?

**Comment by calvinmetcalf** [comment]
yeah at some point, also` _final` too
