### ISSUE TITLE
Error: 'spawn' is not exported by node_modules/rollup-plugin-node-builtins/src/es6/empty.js

### ISSUE THREAD

**Issue by kopax** [calvinmetcalf/rollup-plugin-node-builtins#50]
I have tried to write:

     import { spawn } from 'child_process';

My configuration is : 

https://github.com/rollup-umd/rollup/blob/master/src/index.js#L118

Is this:

- supposed to be supported?
- rollup issue?

Thanks in advance.

Version: `rollup-plugin-node-builtins": "^2.1.2`

**Comment by nivida** [comment]
Could you please add your code example for reproducing this error? 
It doesn't look like a problem of Web3.js isn't importing a file called ``api.key``.

**Comment by calvinmetcalf** [comment]
this isn't something we'd be supporting anyway since it's not somethign that works in the browser

**Comment by kopax** [comment]
Is it not the purpose of that plugin?
It does work in nodejs and should be valid synthax. How can I do? 
For instance, it work with `import {join} from 'path'` which is node not browser.

**Comment by calvinmetcalf** [comment]
this is for the browser
