### ISSUE TITLE
Error: 'Buffer' is not exported by node_modules/buffer/index.js

### ISSUE THREAD

**Issue by emeeks** [calvinmetcalf/rollup-plugin-node-builtins#51]
I updated one of my dependencies on Semiotic and now rollup is complaining that it can't find some of the global vars. I was already using `rollup-plugin-node-builtins` and thought it would as simple as adding `rollup-plugin-node-globals` but no luck. You can see the repo here: https://github.com/nteract/semiotic and the failure detailed in CI here: https://circleci.com/gh/nteract/semiotic/459 (which right now is `Error: 'Buffer' is not exported by node_modules/buffer/index.js` but has been, as I've moved things around, complaining about `process` and whether or not `nextTick` exists.

I'm one of those people that only digs into rollup because of some error or because I have to update to support, say, TypeScript, so if this is related to a different part of the rollup ecosystem or somehow dumb in some other way, just let me know.

**Comment by emeeks** [comment]
I realized this error was in the way I was configuring a test of the resulting distribution and that by listing `process` in the `external` array it was resolved.

**Comment by mikemaccana** [comment]
@emeeks can you please provide your full config?
