### ISSUE TITLE
Cannot find module 'rollup-plugin-node-builtins'

### ISSUE THREAD

**Issue by tyler-johnson** [calvinmetcalf/rollup-plugin-node-builtins#6]
It seems that the `package.json` points the main field to a file in the `dist/` folder, however the distributed copy in NPM is missing the `dist/` folder. I'm guessing it just wasn't built before being published?

**Comment by calvinmetcalf** [comment]
forgot the prepublish script, 1.0.3 should be fixed

**Comment by calvinmetcalf** [comment]
fuckit, made it a post install step in 1.0.4

**Comment by tyler-johnson** [comment]
hehe works for me! thanks

**Comment by kylegmaxwell** [comment]
This just started happening again for me in 1.0.5 so I had to lock it back to 1.0.4.

**Comment by calvinmetcalf** [comment]
ok try 1.0.6
